update usuarios SET usuarioid='100' where nombre= 'Willard Cess';
update usuarios SET fecha_nacimiento='10/10/1990' where pais='Colombia';
INSERT INTO PAISES(NOMBRE) VALUES('SPAIN');
UPDATE PAISES SET NOMBRE='PERÚ' WHERE NOMBRE='Peru';
UPDATE PAISES SET PAIS_ID='90' WHERE NOMBRE='SPAIN';
INSERT INTO PAISES(NOMBRE) VALUES('ANTARTIDA');
INSERT INTO PAISES(NOMBRE) VALUES('Islas Canarias');