ALTER TABLE RESULTADOS 
ADD CONSTRAINT FK_RESULTADOS_USUARIOS 
FOREIGN KEY(USUARIOID) 
REFERENCES USUARIOS(USUARIOID);



ALTER TABLE RESULTADOS
ADD CONSTRAINT FK_RESULTADOS_PARTIDOS
FOREIGN KEY(PARTIDOID) 
REFERENCES PARTIDOS(PARTIDOID);

ALTER TABLE JUGADORESAPUESTAS
ADD CONSTRAINT FK_JUGADORESAPUESTAS_USUARIOS
FOREIGN KEY(USUARIOID)
REFERENCES USUARIOS(USUARIOID);

ALTER TABLE JUGADORESAPUESTAS
ADD CONSTRAINT FK_JUGADORESAPUESTAS_PARTIDOSA
FOREIGN KEY(PARTIDOID) 
REFERENCES PARTIDOS(PARTIDOID);

ALTER TABLE PARTIDOS 
ADD CONSTRAINT FK_PARTIDOS_EQUIPOSL
FOREIGN KEY(LOCALID) 
REFERENCES EQUIPOS(EQUIPOID);

ALTER TABLE PARTIDOS 
ADD CONSTRAINT FK_PARTIDOS_EQUIPOSV
FOREIGN KEY(VISITANTEID) 
REFERENCES EQUIPOS(EQUIPOID);

ALTER TABLE POSIBLESRESULTADOS
ADD CONSTRAINT FK_POSSRES_RESULTADOS 
FOREIGN KEY(RESULTADOID) 
REFERENCES RESULTADOS(ID);

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_PAISES
FOREIGN KEY(PAIS)
REFERENCES PAISES(NOMBRE);

ALTER TABLE PARTIDOS
ADD CONSTRAINT FK_PARTIDOS_TEMPORADS
FOREIGN KEY(TEMPORADAID)
REFERENCES TEMPORADAS(TEMPORADA_ID);