-----CRUDE-----
---PC-APUESTAS
CREATE OR REPLACE PACKAGE PC_APUESTAS IS
    PROCEDURE ADD_APUESTAS_JUGADOR(XIDJUGADOR IN INTEGER, XUSUARIOID IN INTEGER, XFECHAID IN DATE, XGANADORES IN CHAR, XIMPORTE IN NUMBER, XCANTANOTACIONES IN INTEGER, XPAGA IN NUMBER, XPARTIDOID IN INTEGER);    
    PROCEDURE ADD_APUESTAS_RESULTADO(XPARTIDOID IN INTEGER, XUSUARIOID IN NUMBER, XFECHAID IN DATE, XGANADORES IN CHAR, XIMPORTE IN NUMBER, XID IN INTEGER, XRESULTADOID IN INTEGER, XRESULTADO IN VARCHAR, XAFAVORDE IN CHAR, XPAGA IN NUMBER);
    FUNCTION CO_APUESTAS_JUGADOR RETURN SYS_REFCURSOR;
    FUNCTION CO_POSIBLESRESULTADOS RETURN SYS_REFCURSOR;
END PC_APUESTAS;


---PC_USUARIO
CREATE OR REPLACE PACKAGE PC_USUARIO IS
    PROCEDURE ADD_USUARIO(XUSUARIOID IN NUMBER, XNOMBRE IN VARCHAR, XPAIS IN VARCHAR, XFECHA_NACIMIENTO IN DATE);
    PROCEDURE EL_USUARIO(XUSUARIOID IN NUMBER);
    FUNCTION CO_USUARIO RETURN SYS_REFCURSOR;
END PC_USUARIO;


----CRUDI-----

CREATE OR REPLACE PACKAGE BODY PC_USUARIO IS
    PROCEDURE  ADD_USUARIO(XUSUARIOID IN NUMBER, XNOMBRE IN VARCHAR, XPAIS IN VARCHAR, XFECHA_NACIMIENTO IN DATE) IS BEGIN
    INSERT INTO USUARIOS (USUARIOID, NOMBRE, PAIS, FECHA_NACIMIENTO)
    VALUES (XUSUARIOID, XNOMBRE, XPAIS, XFECHA_NACIMIENTO);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'ERROR DE PAQUETES');
    END;
    
    PROCEDURE EL_USUARIO(XUSUARIOID IN NUMBER)IS BEGIN
    DELETE FROM USUARIOS WHERE USUARIOID = XUSUARIOID;
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20104,'ERROR DE PAQUETES');
    END;
    
    FUNCTION CO_USUARIO RETURN SYS_REFCURSOR IS CO_USUARIOS SYS_REFCURSOR;
    
    BEGIN
            OPEN CO_USUARIOS FOR SELECT* FROM USUARIOS;
            RETURN CO_USUARIOS;
    END;
	
    FUNCTION CO_Jugador  RETURN SYS_REFCURSOR IS CO_JUG SYS_REFCURSOR;
		BEGIN
			OPEN CO_JUG  FOR
			SELECT * FROM JUGADORESAPUESTAS;
			RETURN CO_JUG;
	END;
    
END PC_USUARIO;
  


CREATE OR REPLACE PACKAGE BODY PC_APUESTAS IS
    PROCEDURE ADD_APUESTAS_JUGADOR(XIDJUGADOR IN INTEGER, XUSUARIOID IN INTEGER, XFECHAID IN DATE, XGANADORES IN CHAR, XIMPORTE IN NUMBER, XCANTANOTACIONES IN INTEGER, XPAGA IN NUMBER, XPARTIDOID IN INTEGER) IS BEGIN
    INSERT INTO JUGADORESAPUESTAS (IDJUGADOR, USUARIOID, FECHAID, GANADORES, IMPORTE, CANTANOTACIONES, PAGA, PARTIDOID)
    VALUES (XIDJUGADOR, XUSUARIOID, XFECHAID, XGANADORES, XIMPORTE, XCANTANOTACIONES, XPAGA, XPARTIDOID);
        
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20101,'ERROR DE PAQUETES');
    END;
    
    PROCEDURE ADD_APUESTAS_RESULTADO(XPARTIDOID IN INTEGER, XUSUARIOID IN NUMBER, XFECHAID IN DATE, XGANADORES IN CHAR, XIMPORTE IN NUMBER, XID IN INTEGER, XRESULTADOID IN INTEGER, XRESULTADO IN VARCHAR, XAFAVORDE IN CHAR, XPAGA IN NUMBER) IS BEGIN
    INSERT INTO RESULTADOS(PARTIDOID, USUARIOID, FECHAID, GANADORES, IMPORTE, ID)
    VALUES (XPARTIDOID, XUSUARIOID, XFECHAID, XGANADORES, XIMPORTE, XID);
    
    INSERT INTO POSIBLESRESULTADOS(RESULTADOID, RESULTADO, AFAVORDE, PAGA)
    VALUES(XRESULTADOID, XRESULTADO, XAFAVORDE, XPAGA);
    
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20102,'ERROR DE PAQUETES');
    END;
    
    FUNCTION CO_APUESTAS_JUGADOR RETURN SYS_REFCURSOR IS CO_APU_JUG SYS_REFCURSOR;
        BEGIN
            OPEN CO_APU_JUG FOR SELECT* FROM JUGADORESAPUESTAS;
        RETURN CO_APU_JUG;
    END;
    
    FUNCTION CO_POSIBLESRESULTADOS RETURN SYS_REFCURSOR IS CO_POSIBLESRESULTADO SYS_REFCURSOR;
        BEGIN
            OPEN CO_POSIBLESRESULTADO FOR SELECT* FROM POSIBLESRESULTADO;
        RETURN CO_POSIBLESRESULTADO;
    END;
            
END PC_APUESTAS;
