---------------------------Primarias----------------------------------------------------------

ALTER TABLE USUARIOS 
ADD CONSTRAINT PK_USUARIOS 
PRIMARY KEY(USUARIOID);

ALTER TABLE RESULTADOS 
ADD CONSTRAINT PK_RESULTADOS
PRIMARY KEY(ID);
--PARTIDOID, USUARIOID

ALTER TABLE POSIBLESRESULTADOS
ADD CONSTRAINT PK_POSIBLESRESULTADOS 
PRIMARY KEY(RESULTADOID, RESULTADO);

ALTER TABLE JUGADORESAPUESTAS
ADD CONSTRAINT PK_JUGADORESAPUESTAS 
PRIMARY KEY(IDJUGADOR, USUARIOID);

ALTER TABLE PARTIDOS 
ADD CONSTRAINT PK_PARTIDOS
PRIMARY KEY(PARTIDOID);

ALTER TABLE EQUIPOS 
ADD CONSTRAINT PK_EQUIPOS
PRIMARY KEY(EQUIPOID);

ALTER TABLE COMPETICIONES 
ADD CONSTRAINT PK_COMPETICIONES
PRIMARY KEY(COMPETICION_ID);

ALTER TABLE PAISES 
ADD CONSTRAINT PK_PAISES 
PRIMARY KEY(NOMBRE);

ALTER TABLE TEMPORADAS
ADD CONSTRAINT PK_TEMPORADAS
PRIMARY KEY(TEMPORADA_ID);

ALTER TABLE LIGAS
ADD CONSTRAINT PK_LIGAS
PRIMARY KEY(LIGA);