-----------XDISPARADORES----------
DROP TRIGGER ADD_RESULTADOS;
DROP TRIGGER EL_RESULTADOS;
DROP TRIGGER MOD_RESULTADOS;
DROP TRIGGER EL_POSIBLESRESULTADOS;
DROP TRIGGER MOD_POSIBLESRESULTADOS;
DROP TRIGGER EL_JUGADORESAPUESTAS;
DROP TRIGGER MOD_JUGADORESAPUESTAS;
DROP TRIGGER NUEVOUSUARIO;
DROP TRIGGER MODIFICAUSUARIO;
DROP TRIGGER ELIMINAUSUARIO;