-------------XTABLAS----------
DROP TABLE USUARIOS;
DROP TABLE RESULTADOS;
DROP TABLE POSIBLESRESULTADOS;
DROP TABLE JUGADORESAPUESTAS;
DROP TABLE PARTIDOS;
DROP TABLE EQUIPOS;
DROP TABLE COMPETICIONES;
DROP TABLE PAISES;
DROP TABLE LIGAS;

---------XPRIMARIAS------------
ALTER TABLE USUARIOS DROP CONSTRAINT PK_USUARIOS;
ALTER TABLE RESULTADOS DROP CONSTRAINT PK_RESULTADOS;
ALTER TABLE POSIBLESRESULTADOS DROP CONSTRAINT PK_POSIBLESRESULTADOS;
ALTER TABLE JUGADORESAPUESTAS DROP CONSTRAINT PK_JUGADORESAPUESTAS;
ALTER TABLE PARTIDOS DROP CONSTRAINT PK_PARTIDOS;
ALTER TABLE EQUIPOS DROP CONSTRAINT PK_EQUIPOS;
ALTER TABLE COMPETICIONES DROP CONSTRAINT PK_COMPETICIONES;
ALTER TABLE PAISES DROP CONSTRAINT PK_PAISES;
ALTER TABLE TEMPORADAS DROP CONSTRAINT PK_TEMPORADAS;
ALTER TABLE LIGAS DROP CONSTRAINT PK_LIGAS;
----XUNICAS-------
ALTER TABLE USUARIOS DROP CONSTRAINT UK_USUARIOS;
ALTER TABLE PAISES DROP CONSTRAINT UK_PAISES;